server:
  servlet:
    context-path: /seller
  port: 8084


rpc:
  client:
    url: http://localhost:8081/manager/
    basePackage: com.csii.api
spring:
  datasource:
    primary:
      url: jdbc:mysql://192.168.121.181:3309/seller?user=root&password=123456&useUnicode=true&characterEncoding=utf-8
    backup:
      url: jdbc:mysql://192.168.121.181:3309/seller-backup?user=root&password=123456&useUnicode=true&characterEncoding=utf-8
  cache:
    type: hazelcast
  activemq:
    broker-url: tcp://192.168.121.181:61616
    packages:
      trust-all: true
  jpa:
    show-sql: true

logging:
  level:
    com.googlecode.jsonrpc4j: debug

swagger:
  basePackage: com.csii.seller.controller
  title: 销售端API
  description: >
    authId 是由本方提供给接口调用方用于安全控制及身份识别，请在需要此参数的接口上，通过请求头传递。
    sign 是接口调用方使用私钥对请求对象中的非空字段按字典排序之后的JSON字符串进行的签名。请在需要此参数的接口上，通过请求头传递。
