spring:
  datasource:
    url: jdbc:mysql://192.168.121.181:3309/manager?user=root&password=123456&useUnicode=true&characterEncoding=utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
  jpa:
    show-sql: true
  activemq:
    broker-url: tcp://192.168.121.181:61616
  jms:
    pub-sub-domain: true
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
server:
  servlet:
    context-path: /manager
  port: 8081

swagger:
  groupName: manger
  basePackage: com.csii.manager.controller


logging:
  level:
    com.googlecode.jsonrpc4j: debug
